### ISSUE TITLE
Show job status

### ISSUE THREAD

**Issue by lbradstreet** [lbradstreet/onyx-dashboard#19]
Can be running / completed / killed. 

Should also grey out job management options based on these.  Will consult @MichaelDrogalis for the best way to track these.

**Comment by MichaelDrogalis** [comment]
@lbradstreet In the replica, killed jobs are listed under the `:killed-jobs`, completed jobs can be derived from [common](https://github.com/MichaelDrogalis/onyx/blob/0.5.x/src/onyx/log/commands/common.clj#L111-115), and running jobs are all the rest. :)

**Comment by lbradstreet** [comment]
Done. Also shows the status in the job info panel with the task scheduler.
