### ISSUE TITLE
Implement log paging

### ISSUE THREAD

**Issue by lbradstreet** [lbradstreet/onyx-dashboard#2]
Currently only the latest 100 log entries are displayed in the front end (performance suffers otherwise). Users should be able to scroll or page through these log entries.

**Comment by lbradstreet** [comment]
Can hopefully use http://facebook.github.io/fixed-data-table/

Tentatively going to try for 0.1. Non essential.

**Comment by MichaelDrogalis** [comment]
@lbradstreet Yeah, this is a good idea IMO. :)

**Comment by lbradstreet** [comment]
Do you mean 100 entries are enough or we should prioritise log paging? Think you mean the latter

**Comment by MichaelDrogalis** [comment]
The latter, yes.

**Comment by lbradstreet** [comment]
Basic log paging is implemented. There are a couple of issues still. If the log is live and you switch to the next page it will probably continue to stream past whereas it really should be fixed you have a chance to read it.

Secondly, it jumps to the top of the page when you page the table :/

**Comment by lbradstreet** [comment]
Paging should be fixed on particular entries as more entries stream in. Need to test this a bit further as there could be bugs.
