### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by lbradstreet** [lbradstreet/onyx-dashboard#20]
Issue for tracking smaller release tasks
- [x] ensure we make the change to Onyx to dynamically set job scheduler
- [x] test performance on big logs
- [x] test uberjar / advanced mode
- [x] write blog post
- [ ] create screen cast
- [x] should probably test against that Firefox browser I've heard about
- [x] release Onyx 0.5.2

**Comment by lbradstreet** [comment]
Getting there

**Comment by lbradstreet** [comment]
Performance on big logs is reasonable enough. I can load 60 log entries per second and that's off a ZK instance on EC2, which is the bottleneck.

**Comment by lbradstreet** [comment]
Uberjar builds from circle should be working now. I will start having them be uploaded to S3 or something with a tag for the onyx version they use.

**Comment by MichaelDrogalis** [comment]
We should probably make the dashboard version lockstep with Onyx. So we'd start at `0.5.2`.

**Comment by lbradstreet** [comment]
Excellent idea! Maybe with a fourth digit so we can release independently?

**Comment by MichaelDrogalis** [comment]
That sounds perfect.

**Comment by lbradstreet** [comment]
Woot. Done!
