### ISSUE TITLE
Need a way to supply a job scheduler when selecting a deployment

### ISSUE THREAD

**Issue by lbradstreet** [lbradstreet/onyx-dashboard#22]
Any solution for this will probably be awkward unless we store it somewhere.

**Comment by MichaelDrogalis** [comment]
Done in https://github.com/MichaelDrogalis/onyx/commit/150157b7b9cd849313f30eccc070a23a3be93d55

Will cut a new release early next week once we're sure this is an okay change.

**Comment by lbradstreet** [comment]
Bumped to snapshot release and working nicely.
