### ISSUE TITLE
Create a component for viewing EDN

### ISSUE THREAD

**Issue by lbradstreet** [lbradstreet/onyx-dashboard#7]
Ankha is only really meant for debugging purposes and isn't cutting it.

Could just use codemirror in read only mode http://codemirror.net/ which is what I think Oxide uses.

**Comment by MichaelDrogalis** [comment]
Oxide is using AceEditor, actually. I think either will be fine though.

**Comment by lbradstreet** [comment]
Oh right. Switched them around in my mind. Was gonna check anyway. I'll use AceEditor since you've done the hard work for me :D

**Comment by lbradstreet** [comment]
@MichaelDrogalis did good.
